### ISSUE TITLE
[Dummy] - implement additional props

### ISSUE THREAD

**Issue by isBatak** [isBatak/theme-ui-expansion-pack#3]
- [ ] isAnimated - simple gradient animation for loading skeletons
- [ ] width
- [ ] height

**Comment by kristian240** [comment]
I added width and height props. Also, I added a simple pulse animation that animates opacity. Do you have any other idea on how to animate `Dummy` component?  I found this solution implemented on `chakra-ui` but there is also a way to pass 2 colors, start and end colors and animation is fading from start to end color. https://chakra-ui.com/skeleton#skeleton-color
